### PR TITLE
Updated to latest RTOS fork and lowrisc-nix

### PR DESCRIPTION
**Pull request by HU90m**
- Updated to latest version of lowRISC RTOS fork
- Updated lowrisc-nix version
  - We'll need the latest version of the compiler to be able to build the
upstream CHERIoT RTOS.

### CODE REVIEW

**Comment by AlexJones0** [comment]
Force pushes have rebased on latest `main`, and updated the software (usbdev utils, usbdev test, plic test) to use the refactored USB device driver so that all tests should still work.

**Review by HU90m — COMMENTED** [review]
My own PR so I can't give it a green tick, but I would if I could. Thanks Alex. Do merge

**Review by AlexJones0 — APPROVED** [review]
Approving because I'm happy with @HU90m's build changes and he appears to be happy with my corresponding software changes.

**Review by marnovandermaas — APPROVED** [review]
Looks reasonable to me. We still need some more updates in our RTOS fork, but we can always bump it later.

**Pull request merged**
