### PR TITLE
SPI IRQ test

### PR DESCRIPTION
**Pull request by alees24**
Testing of SPI interrupts.

### CODE REVIEW

**Review by marnovandermaas — COMMENTED** [review]
Hmmm, it looks like the pinmux test is failing after the interrupt test is added. Does the interrupt test leave the flash SPI in a different state than it started?

**Comment by marnovandermaas** [comment]
I assume it's because of this line: `spi->control = SonataSpi::ControlInternalLoopback | SonataSpi::ControlTransmitEnable | SonataSpi::ControlReceiveEnable | (encRxWatermark << 8) | (encTxWatermark << 4);`
We might need to undo it after the interrupt test or set the correct control value in the pinmux SPI test.

**Comment by alees24** [comment]
> I assume it's because of this line: `spi->control = SonataSpi::ControlInternalLoopback | SonataSpi::ControlTransmitEnable | SonataSpi::ControlReceiveEnable | (encRxWatermark << 8) | (encTxWatermark << 4);` We might need to undo it after the interrupt test or set the correct control value in the pinmux SPI test.

This isn't a problem with the interrupt test. Altered signalling to the SPI DPI model in simulation with the pinmux changes has exposed the fact that the model was not happy with SCK toggling when CS is deasserted (PR #292).

**Review by marnovandermaas — APPROVED** [review]
Thanks for fixing this. I think this is good to have in CI.

**Pull request merged**
