### PR TITLE
Fixed interrupt indices

### PR DESCRIPTION
**Pull request by HU90m**
After creating https://github.com/lowRISC/sonata-system/issues/137 , realised the comments wouldn't take long to fix, so fixed them.

*Vim's <kbd>Ctrl</kbd>+<kbd>A</kbd> is a god send I reach for a surprising amount.*

### CODE REVIEW

**Comment by HU90m** [comment]
The CI software build failed due to a network error; it can be happily ignored.

**Review by nbdd0121 — APPROVED** [review]

**Comment by HU90m** [comment]
It may be nicer to do something like the following, so these are checked at compile time.

```sv
  logic [181:0] intr_vector;
  always_comb begin : interrupt_vector
    intr_vector[72 +: 110] = 110'b0;
    intr_vector[71 +: 1] = uart4_rx_parity_err_irq;
    intr_vector[70 +: 1] = uart4_rx_timeout_irq;
    intr_vector[69 +: 1] = uart4_rx_break_err_irq;
    intr_vector[68 +: 1] = uart4_rx_frame_err_irq;
    intr_vector[67 +: 1] = uart4_rx_overflow_irq;
    intr_vector[66 +: 1] = uart4_tx_empty_irq;
    intr_vector[65 +: 1] = uart4_rx_watermark_irq;
    intr_vector[64 +: 1] = uart4_tx_watermark_irq;

    intr_vector[63 +: 1] = uart3_rx_parity_err_irq;
    intr_vector[62 +: 1] = uart3_rx_timeout_irq;
    intr_vector[61 +: 1] = uart3_rx_break_err_irq;
    intr_vector[60 +: 1] = uart3_rx_frame_err_irq;
    intr_vector[59 +: 1] = uart3_rx_overflow_irq;
    intr_vector[58 +: 1] = uart3_tx_empty_irq;
    intr_vector[57 +: 1] = uart3_rx_watermark_irq;
    intr_vector[56 +: 1] = uart3_tx_watermark_irq;

    intr_vector[55 +: 1] = uart2_rx_parity_err_irq;
    intr_vector[54 +: 1] = uart2_rx_timeout_irq;
    intr_vector[53 +: 1] = uart2_rx_break_err_irq;
    intr_vector[52 +: 1] = uart2_rx_frame_err_irq;
    intr_vector[51 +: 1] = uart2_rx_overflow_irq;
    intr_vector[50 +: 1] = uart2_tx_empty_irq;
    intr_vector[49 +: 1] = uart2_rx_watermark_irq;
    intr_vector[48 +: 1] = uart2_tx_watermark_irq;

    intr_vector[47 +: 1] = spi_eth_irq;

    intr_vector[46 +: 1] = i2c1_host_timeout_irq;
    intr_vector[45 +: 1] = i2c1_unexp_stop_irq;
    intr_vector[44 +: 1] = i2c1_acq_full_irq;
    intr_vector[43 +: 1] = i2c1_tx_threshold_irq;
    intr_vector[42 +: 1] = i2c1_tx_stretch_irq;
    intr_vector[41 +: 1] = i2c1_cmd_complete_irq;
    intr_vector[40 +: 1] = i2c1_sda_unstable_irq;
    intr_vector[39 +: 1] = i2c1_stretch_timeout_irq;
    intr_vector[38 +: 1] = i2c1_sda_interference_irq;
    intr_vector[37 +: 1] = i2c1_scl_interference_irq;
    intr_vector[36 +: 1] = i2c1_nak_irq;
    intr_vector[35 +: 1] = i2c1_rx_overflow_irq;
    intr_vector[34 +: 1] = i2c1_acq_threshold_irq;
    intr_vector[33 +: 1] = i2c1_rx_threshold_irq;
    intr_vector[32 +: 1] = i2c1_fmt_threshold_irq;

    intr_vector[31 +: 1] = i2c0_host_timeout_irq;
    intr_vector[30 +: 1] = i2c0_unexp_stop_irq;
    intr_vector[29 +: 1] = i2c0_acq_full_irq;
    intr_vector[28 +: 1] = i2c0_tx_threshold_irq;
    intr_vector[27 +: 1] = i2c0_tx_stretch_irq;
    intr_vector[26 +: 1] = i2c0_cmd_complete_irq;
    intr_vector[25 +: 1] = i2c0_sda_unstable_irq;
    intr_vector[24 +: 1] = i2c0_stretch_timeout_irq;
    intr_vector[23 +: 1] = i2c0_sda_interference_irq;
    intr_vector[22 +: 1] = i2c0_scl_interference_irq;
    intr_vector[21 +: 1] = i2c0_nak_irq;
    intr_vector[20 +: 1] = i2c0_rx_overflow_irq;
    intr_vector[19 +: 1] = i2c0_acq_threshold_irq;
    intr_vector[18 +: 1] = i2c0_rx_threshold_irq;
    intr_vector[17 +: 1] = i2c0_fmt_threshold_irq;

    intr_vector[16 +: 1] = uart1_rx_parity_err_irq;
    intr_vector[15 +: 1] = uart1_rx_timeout_irq;
    intr_vector[14 +: 1] = uart1_rx_break_err_irq;
    intr_vector[13 +: 1] = uart1_rx_frame_err_irq;
    intr_vector[12 +: 1] = uart1_rx_overflow_irq;
    intr_vector[11 +: 1] = uart1_tx_empty_irq;
    intr_vector[10 +: 1] = uart1_rx_watermark_irq;
    intr_vector[9 +: 1]  = uart1_tx_watermark_irq;

    intr_vector[8 +: 1]  = uart0_rx_parity_err_irq;
    intr_vector[7 +: 1]  = uart0_rx_timeout_irq;
    intr_vector[6 +: 1]  = uart0_rx_break_err_irq;
    intr_vector[5 +: 1]  = uart0_rx_frame_err_irq;
    intr_vector[4 +: 1]  = uart0_rx_overflow_irq;
    intr_vector[3 +: 1]  = uart0_tx_empty_irq;
    intr_vector[2 +: 1]  = uart0_rx_watermark_irq;
    intr_vector[1 +: 1]  = uart0_tx_watermark_irq;

    intr_vector[0 +: 1]  = 1'b0; // This is a special case and tied to zero.
  end : interrupt_vector
```

**Comment by nbdd0121** [comment]
I think assign should also work?

**Comment by HU90m** [comment]
> I think assign should also work?

I don't think one can do an assign block so it would have to be the following, which is a little uglier in my opinion.

```sv
assign intr_vector[72 +: 110] = 110'b0;
assign intr_vector[71 +: 1] = uart4_rx_parity_err_irq;
assign intr_vector[70 +: 1] = uart4_rx_timeout_irq;
assign intr_vector[69 +: 1] = uart4_rx_break_err_irq;
assign intr_vector[68 +: 1] = uart4_rx_frame_err_irq;
assign intr_vector[67 +: 1] = uart4_rx_overflow_irq;
assign intr_vector[66 +: 1] = uart4_tx_empty_irq;
assign intr_vector[65 +: 1] = uart4_rx_watermark_irq;
assign intr_vector[64 +: 1] = uart4_tx_watermark_irq;

assign intr_vector[63 +: 1] = uart3_rx_parity_err_irq;
assign intr_vector[62 +: 1] = uart3_rx_timeout_irq;
assign intr_vector[61 +: 1] = uart3_rx_break_err_irq;
assign intr_vector[60 +: 1] = uart3_rx_frame_err_irq;
assign intr_vector[59 +: 1] = uart3_rx_overflow_irq;
assign intr_vector[58 +: 1] = uart3_tx_empty_irq;
assign intr_vector[57 +: 1] = uart3_rx_watermark_irq;
assign intr_vector[56 +: 1] = uart3_tx_watermark_irq;

assign intr_vector[55 +: 1] = uart2_rx_parity_err_irq;
assign intr_vector[54 +: 1] = uart2_rx_timeout_irq;
assign intr_vector[53 +: 1] = uart2_rx_break_err_irq;
assign intr_vector[52 +: 1] = uart2_rx_frame_err_irq;
assign intr_vector[51 +: 1] = uart2_rx_overflow_irq;
assign intr_vector[50 +: 1] = uart2_tx_empty_irq;
assign intr_vector[49 +: 1] = uart2_rx_watermark_irq;
assign intr_vector[48 +: 1] = uart2_tx_watermark_irq;

assign intr_vector[47 +: 1] = spi_eth_irq;

assign intr_vector[46 +: 1] = i2c1_host_timeout_irq;
assign intr_vector[45 +: 1] = i2c1_unexp_stop_irq;
assign intr_vector[44 +: 1] = i2c1_acq_full_irq;
assign intr_vector[43 +: 1] = i2c1_tx_threshold_irq;
assign intr_vector[42 +: 1] = i2c1_tx_stretch_irq;
assign intr_vector[41 +: 1] = i2c1_cmd_complete_irq;
assign intr_vector[40 +: 1] = i2c1_sda_unstable_irq;
assign intr_vector[39 +: 1] = i2c1_stretch_timeout_irq;
assign intr_vector[38 +: 1] = i2c1_sda_interference_irq;
assign intr_vector[37 +: 1] = i2c1_scl_interference_irq;
assign intr_vector[36 +: 1] = i2c1_nak_irq;
assign intr_vector[35 +: 1] = i2c1_rx_overflow_irq;
assign intr_vector[34 +: 1] = i2c1_acq_threshold_irq;
assign intr_vector[33 +: 1] = i2c1_rx_threshold_irq;
assign intr_vector[32 +: 1] = i2c1_fmt_threshold_irq;

assign intr_vector[31 +: 1] = i2c0_host_timeout_irq;
assign intr_vector[30 +: 1] = i2c0_unexp_stop_irq;
assign intr_vector[29 +: 1] = i2c0_acq_full_irq;
assign intr_vector[28 +: 1] = i2c0_tx_threshold_irq;
assign intr_vector[27 +: 1] = i2c0_tx_stretch_irq;
assign intr_vector[26 +: 1] = i2c0_cmd_complete_irq;
assign intr_vector[25 +: 1] = i2c0_sda_unstable_irq;
assign intr_vector[24 +: 1] = i2c0_stretch_timeout_irq;
assign intr_vector[23 +: 1] = i2c0_sda_interference_irq;
assign intr_vector[22 +: 1] = i2c0_scl_interference_irq;
assign intr_vector[21 +: 1] = i2c0_nak_irq;
assign intr_vector[20 +: 1] = i2c0_rx_overflow_irq;
assign intr_vector[19 +: 1] = i2c0_acq_threshold_irq;
assign intr_vector[18 +: 1] = i2c0_rx_threshold_irq;
assign intr_vector[17 +: 1] = i2c0_fmt_threshold_irq;

assign intr_vector[16 +: 1] = uart1_rx_parity_err_irq;
assign intr_vector[15 +: 1] = uart1_rx_timeout_irq;
assign intr_vector[14 +: 1] = uart1_rx_break_err_irq;
assign intr_vector[13 +: 1] = uart1_rx_frame_err_irq;
assign intr_vector[12 +: 1] = uart1_rx_overflow_irq;
assign intr_vector[11 +: 1] = uart1_tx_empty_irq;
assign intr_vector[10 +: 1] = uart1_rx_watermark_irq;
assign intr_vector[9 +: 1]  = uart1_tx_watermark_irq;

assign intr_vector[8 +: 1]  = uart0_rx_parity_err_irq;
assign intr_vector[7 +: 1]  = uart0_rx_timeout_irq;
assign intr_vector[6 +: 1]  = uart0_rx_break_err_irq;
assign intr_vector[5 +: 1]  = uart0_rx_frame_err_irq;
assign intr_vector[4 +: 1]  = uart0_rx_overflow_irq;
assign intr_vector[3 +: 1]  = uart0_tx_empty_irq;
assign intr_vector[2 +: 1]  = uart0_rx_watermark_irq;
assign intr_vector[1 +: 1]  = uart0_tx_watermark_irq;

assign intr_vector[0 +: 1]  = 1'b0; // This is a special case and tied to zero.
```

**Comment by marnovandermaas** [comment]
Thanks for catching this (my typo).

**Comment by HU90m** [comment]
@nbdd0121 @marnovandermaas do you prefer the `always_comb` block or the many `assign`s?

**Comment by marnovandermaas** [comment]
> @nbdd0121 @marnovandermaas do you prefer the `always_comb` block or the many `assign`s?

I think `always_comb` looks a bit cleaner.

**Pull request merged**
