### PR TITLE
Remove generated PLIC README.md

### PR DESCRIPTION
**Pull request by GregAC**
The documentation isn't required for our generated PLIC and it causes breakages in our document lint flow.

### CODE REVIEW

**Comment by GregAC** [comment]
CI is broken without this

**Comment by GregAC** [comment]
CI failure is a timeout in the simulation, not sure why as the tests complete and output the correct message to indicate this, investigating now

**Comment by GregAC** [comment]
It's a failure in the CHERIoT test suite, not entirely sure what's happening there. I had noted binaries build in 'sonata-software' weren't working properly but I put that down to sonata-software not having the correct CHERIoT RTOS for the hardware. Also not clear why the PLIC changes would have broken the test suite

**Comment by HU90m** [comment]
> It's a failure in the CHERIoT test suite, not entirely sure what's happening there. I had noted binaries build in 'sonata-software' weren't working properly but I put that down to sonata-software not having the correct CHERIoT RTOS for the hardware. Also not clear why the PLIC changes would have broken the test suite

https://github.com/CHERIoT-Platform/cheriot-rtos/blob/e7f4962da8c9e24066f112afd2cacb6a1e165abe/sdk/boards/sonata-prerelease.json#L158

**Pull request merged**
